@baseUrl = http://localhost:3000/api

### 获取客户信息列表 - 未授权测试
GET {{baseUrl}}/customer-info/list

### 获取客户信息列表 - 使用 Session Token
GET {{baseUrl}}/customer-info/list
Cookie: authjs.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiMjdjQzA0V0toaXVJbUNVOEtSOUpFREFhS0RNemVILXgzU0Vqc3pqRnZBYkFEUjE4VzVkWVB2Y0dSZXUyQkZhRnY2MGMxSGlSUVJyUk95bDFNR09VNVEifQ..z0qUFTvNz9tLvZZCaH5hrw.fxCtXy10YFjsp3VNbqMRHOgHTlX-YgkeYFyz9fmQOAc-5YuW1LjA7hjwScutTtl7gmsND_f_kvJw1izGyQqlXWJoyXNhVJ25pcvBFoG_7TRLomvgOqkk3xHKRG1klFCPbBHwXT67q8i7U0akmbVowA0ilsAUAwkrskD94oNazPWO0YW6nRbTIcg0gDep6bkh3Ij2Hs2pMxmjJMsugV68kdtZNaeTMEholw9wkg1isJVNsnAVE8TJZs2-j-2E7eu7BtvYh6vtAy-ss2WEA1BO-ZdC7d1b7A_YhwgSc4eQjwffbxVIoJV0J9LFc_xQ9kDsuE4pNkj-gFtWP7AfMbT2gJ8uSgubD0rGC3GdCiYqGv7K2HRcc-RpZGc3UswXaLrjt3Ajtdxd2dpTLclJdogtGmyaR8uA2khXmLy-kBPWwRkPS3kO0Qigc0jKO8vgXJ-3SEC6hqpfXV3WkCTvkpVZOv8XwFXnjX6BUwMjVwI7lwahVPNf_x7BQterp4reSG9rcphngyamsf-DyOMkT4k9xlPabRT-0CeFyzA1RP-YawqDtHj1gDB5x4eTmcF51DaujWx-sp7lB6XueIV8zpyw2JvnEG4znMVM7mMPRXlDUO8.7QVtP4UwQ78ET7V7pX7F591z3EhyBVtRLHUukrQg4ow 