// Blocked email domains used to prevent disposable/abusive registrations.
// Keep this list in sync with security docs if needed.
export const BLOCKED_EMAIL_DOMAINS = [
  "drmail.in",
  "mriscan.live",
  "powerscrews.com",
  "moakt.ws",
  "moakt.cc",
  "moakt.co",
  "bareed.ws",
  "tmails.net",
  "teml.net",
  "disbox.org",
  "tmpbox.net",
  "tmpmail.net",
  "tmpmail.org",
  "mailshan.com",
  "aminating.com",
  "noidem.com",
  "skateru.com",
  "tmail.ws",
  "tmpeml.com",
  "qqveo.online",
  "ablyd.com",
  "pzejw.com",
  "wbmta.com",
  "atomicmail.io",
  "atminmail.com",
  "tiffincrane.com",
  "allfreemail.net",
  "usiver.com",
  "tlexes.com",
  "hiepth.com",
  "etenx.com",
  "bitmens.com",
  "rograc.com",
  "10minmail.pro",
  "10minutes.email",
  "gddcorp.com",
  "concu.net",
  "heheee.com",
  "mailba.uk",
  "onmailflare.com",
  "tiksofi.uk",
  "priyo.ovh",
  "forexnews.bg",
  "forexzig.com",
  "ro.ru",
  "webxios.pro",
  "yopmail.com",
  "quiet-branch.com",
  "radiant-flow.org",
  "uiemail.com",
  "wtwtt.com",
  "lorkex.com",
  "fanlvr.com",
  "gamegta.com",
  "gta5hx.com",
  "djkux.com",
  "no.vsmailpro.com",
  "suvvs.com",
  "bbcvt.com",
  "koletter.com",
  "jstmail.com",
  "f1t.online",
  "arqsis.com",
  "fontfee.com",
  "capiena.com",
  "opemails.com",
  "bdnets.com",
  "trashlify.com",
  "0ut.online",
  "re146.dev",
  "necub.com",
  "easymailer.live",
  "audince.com",
  "moonfee.com",
  "sharklasers.com",
  "dunefee.com",
  "picoaxis.com",
  "faraby.net",
  "priyo-mail.com",
  "priyomail.in",
  "priyomail.net",
  "nrehi.com",
  "usm.ovh",
  "mailp.org",
  "omailo.top",
  "xenta.cfd",
  "scopevps.com",
  "basefast.net",
  "hivespark.net",
  "tempzulu.com",
  "orbitfast.net",
  "vectorsonata.com",
  "chaossonata.com",
  "spaceeclipse.com",
  "hubbeta.org",
  "orbitcomet.org",
  "sourcesigma.net",
  "briefinnovation.com",
  "primepixel.org",
  "scalarnova.org",
  "spaceblink.net",
  "pidelta.net",
  "vaultcortex.com",
  "pispectrum.org",
  "portalforge.org",
  "asyncpioneer.com",
  "autorambler.ru",
  "byom.de",
  "inbox.eu",
  "school.vin",
  "dunkos.xyz",
  "10mail.xyz",
  "dropmail.me",
  "emltmp.com",
  "spymail.one",
  "mailpwr.com",
  "femailtor.com",
  "inwagit.com",
  "raligaan.com",
  "cherobe.com",
  "keevle.com",
  "haotuwu.com",
  "lovleo.com",
  "wyoxafp.com",
  "webxio.pro",
  "rungel.net",
  "snakement.com",
  "virgilian.com",
  "protectsmail.net",
  "rickix.com",
  "purfait.com",
  "horizonspost.com",
  "mustaer.com",
  "fxzig.com",
  "oqqaj.com",
  "denipl.net",
  "denipl.com",
  "4cloud.pro",
  "illubd.com",
  "xghff.com",
  "ilbudre.com",
  "bltiwd.com",
  "ruutukf.com",
  "psovv.com",
  "kemail.uk",
  "naprb.com",
  "lawicon.com",
  "hetzez.com",
  "hook2ad.com",
  "ozsaip.com",
  "temp.ly",
] as const;

const BLOCKED_EMAIL_DOMAIN_SET = new Set(BLOCKED_EMAIL_DOMAINS);

export function getEmailDomain(email: string | null | undefined): string | null {
  if (!email) return null;
  const atIndex = email.lastIndexOf("@");
  if (atIndex <= -1 || atIndex >= email.length - 1) return null;
  const domain = email.slice(atIndex + 1).trim().toLowerCase();
  return domain ? domain : null;
}

function normalizeDomain(value: string | null | undefined): string | null {
  if (!value) return null;
  const domain = value.trim().toLowerCase();
  return domain ? domain : null;
}

export function isBlockedEmailDomain(emailOrDomain: string | null | undefined): boolean {
  const domain = emailOrDomain?.includes("@") ? getEmailDomain(emailOrDomain) : normalizeDomain(emailOrDomain);
  if (!domain) return false;
  return BLOCKED_EMAIL_DOMAIN_SET.has(domain);
}
